language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_deps
- ./travis-tool.sh install_r devtools microbenchmark knitr arules pbapply memoise
  stringr testthat
- ./travis-tool.sh install_github robertzk/Ramd
- ./travis-tool.sh install_github robertzk/stagerunner robertzk/tundra
- ./travis-tool.sh install_github robertzk/statsUtils robertzk/mungebits
- ./travis-tool.sh install_github robertzk/syberiaMungebits
- ./travis-tool.sh install_github robertzk/syberiaStages robertzk/syberiaStructure
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
    rooms:
      secure: KIoNNEPjpXGUiFyK9GPmOERQYVwXHfq/O5kuZMSd322/lMMQRGYiDJdUQvbnLI6hI8BhPkxZTAUN4aP6Pyov+kabXIIopm0d/rJp6NE9Qq+MBBR6srKNou5wTD9xm4NGTnT/Tk6UvKoUgCW0+n+1FCWSnzQwN95PxhhSSXT+rW4=
